project:
  type: book

book:
  title: "Validation of the Sleep Acceptance Scale"
  author: "Marwin Carmo"
  
  date: "12/14/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - '01_data-cleaning.qmd'
    - '02_data-screening.qmd'
    - '03_dimensionality-analysis.qmd'
    - '04_invariance.qmd'
    - '05_reliability.qmd'
    - summary.qmd
    - references.qmd
  page-navigation: true
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

