project:
  type: book

book:
  title: "Validation of the Sleep Acceptance Scale"
  author: 
    - name: "Marwin Carmo, University of California, Davis"
  repo-url: https://github.com/hadley/r4ds/
  
  date: "12/14/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - '01_data-cleaning.qmd'
    - '02_data-screening.qmd'
    - '03_dimensionality-analysis.qmd'
    - '04_invariance.qmd'
    - '05_reliability.qmd'
    - summary.qmd
    - references.qmd
  page-navigation: true
bibliography: bibliography/references.bib
csl: bibliography/apa7.csl

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

