# Preface {.unnumbered}

This page was developed as the final project of [Dr. Emorie Beck](https://psychology.ucdavis.edu/people/edbeck)'s course [Data Cleaning and Management](https://emoriebeck.github.io/psc290-data-FQ23/), taught at University of California, Davis in the Fall quarter of 2023.

## Background

This project aims to create a comprehensive pipeline for validating the Sleep Acceptance Scale (SAS), an instrument designed to evaluate people's acceptance of sleep problems. The data for this project come from adults between 18 and 59 living in Brazil who were surveyed online using REDCap.

Here, I do not discuss the results of the analyses in-depth as they are expected to be developed in a future publication in a scientific journal. What will be shown in this project are the analyses' code and outputs that usually do not fit into a traditional scientific publication.  


## Motivation

There are two main goals that I wish to achieve with this project. First, it is to make the data analysis phase of this research project transparent and accessible to the reader. Further, it is aimed to be a "living" document where the readers can make suggestions or critiques to improve the quality of the work. I also hope that by sharing the code and outputs in an online book format, researchers with limited or no knowledge of R programming can 

Although this document was designed to be accessed independently of the formal journal publication, it can also serve as supplementary material to the manuscript. Creating a fully reproducible manuscript would be challenging because the co-authors of this research project do not work with R. With this document, at least the data analysis can be shared in a reproducible format.

## Approach

Thanks to a suggestion from Dr. Emorie, this project was redesigned to the format of an HTML [Quarto book](https://quarto.org/docs/books/). This format allows us to easily combine multiple `.qmd` documents into a single manuscript. Each "chapter" in this book corresponds to a different step of the analysis. This way, the scripts can be executed independently or bundled in a single file.

To create this product, I started a new RStudio project using the Quarto book template. Then, different `.qmd` files were created for each step of the analysis and saved in the project's general folder. Additionally, a subfolder for the data was created, containing the raw data, the cleaned data from step 1, and intermediate outputs saved to optimize the rendering of the document.

The project was also made as a [Github repository](https://github.com/marwincarmo/sas), available publicly. Once finished, the book was hosted as a website on Github Pages, available at <https://marwincarmo.github.io/sas/>

## Reflection

Several layers of concepts taught in the course were used to create this project. Because the ultimate goal was to create a reproducible analysis script, it needed to be constructed using a project-based approach, organizing the files in a hierarchical folder structure. To have the data set ready for the analyses, it had to undergo some steps such as transforming date columns, creating new variables based on existing ones, re-coding, treating missing values, pivoting, manipulating strings, and others. Functions for grouping, selecting and filtering were also used frequently throughout the project. 

Although the end product has accomplished its goal, this project has limitations that were not addressed during its development and room for improvement in the future. For instance, it was not pre-registered. Although the current analysis plan has changed in some aspects compared to the initial proposition, documenting these differences would facilitate the inspection of those changes by reviewers and interested readers. Another fundamental limitation is the lack of a data dictionary and a codebook. These files are important to ease the re-use of the data and should be developed shortly. This project also lacks comments on the code chunks. Adding comments will help future re-analyses and is instructive for people interested in using pieces of the code in their work.

This was the first project done aiming to adopt a fully open and reproducible framework. Coding not only for myself but for others who might want to reproduce the same analyses was challenging but rewarding. Working on this project proved to be an exciting opportunity to put into practice many of the ideas discussed in class. It has also helped me build my intuitions in creating projects integrating human and machine readability.