# Introduction

Insomnia is a disorder related to dissatisfaction with the duration or quality of sleep. It can be a source of distress and impairment by decreasing productivity and lowering energy to engage in social activities [@americanpsychiatricassociation2013].

Cognitive and behavioral models of insomnia emphasize the role of sleep-related cognitions as maintainers of insomnia [@espie2006; @harvey2002; @lundh2005; @morin1993; @ong2012; @perlis1997]. This disorder is linked to a stringent attachment to sleep needs and expectations, which feeds worry, thought suppression, and rumination [@lundh2005; @ong2012]. There is compelling evidence that lower levels of psychological flexibility – from which acceptance is a process – are linked to symptoms of depression and anxiety [@bai2020; @bluett2014; @ruiz2010; @twohig2017]. Additionally, psychological inflexibility correlates with higher levels of sleep difficulty even after controlling for the effect of depressive symptoms [@kato2016].

The Sleep Problem Acceptance Questionnaire (SPAQ) [@bothelius2015] is the only measure of acceptance of sleep difficulties developed so far. Because its items were developed with a focus on people with severe sleep problems, this questionnaire has limited application with good sleepers or with those with light to mild sleep problems.  Additionally, general tools for measuring acceptance do not address sleep-related behaviors. For such reasons, we developed a new measure of sleep acceptance, titled **Sleep Acceptance Scale (SAS)**.


## Methods

### Participants

Participants we primarily found through online advertisements, specifically on the social media accounts of the General Hospital of the University of São Paulo, School of Medicine (HC-FMUSP). The data collection period was from May 2021 to July 2022, and we aimed to have both participants with and without insomnia complaints. The first group consisted of individuals already enrolled in an experimental behavioral treatment for insomnia, which this study is a part of. To include participants without insomnia, we requested volunteers who believed they had no sleeping issues. All the participants were natural from Brazil. To be included in the study, participants must be between 18 and 59 years of age and have no reported difficulties reading or writing in Portuguese--SAS was first developed in Portuguese and then translated do English.

### Measures

1. *Sleep Acceptance Scale (SAS)*: Developed as a 6-item self-report questionnaire rated using a scale ranging from 1 (never) to 7 (always), such that high scores indicate lower sleep acceptance. Its items are:

```{r include=FALSE}
tibble::tribble(
  ~Item, ~Statement,
  "1" , "I try to control my sleep by forcing it to happen, or by being too rigid about my sleep schedule.",
  "2" , "I avoid making plans or doing things I enjoy or need to do because of my sleep.",
  "3" ,"The thought of going to sleep makes me uneasy.",
  "4" ,"I have negative feelings towards my sleep.",
  "5" ,"My worries, thoughts, and feelings about my sleep interfere with how I go about my daily life.",
  "6" ,"I am scared of not being able to fall asleep."
) |> 
  kableExtra::kbl()
```

2. *Insomnia Severity Index (ISI)* [@bastien2001; @morin2011a]: An 7-item questionnaire to assess insomnia severity and its impact on the patient's life. Raters use a 5-point scale ranging from 0 (no problem) to 4 (very severe problem).

3.  *The Hospital Anxiety and Depression Scale (HADS)* [@zigmond1983hospital]: This scale assesses psychological distress in non-psychiatric patients. It contains a two-factor structure with seven items assessing Anxiety plus seven other items measuring Depression.

4. *Sleep Problem Acceptance Questionnaire (SPAQ)* [@bothelius2015]: An 8-itens  instrument that measures the acceptance of sleep difficulties. The SPAQ contains the subscales "Activity Engagement" and "Willingness," with four items composing each factor; respondents rate them on a 7-point scale, where 0 means “Disagree,” and 6 indicates "Completely
agree." 

### Statistical Analyses

1. [Data screening and item evaluation](02_data-screening.qmd)
2. [Assessment of the underlying structure](03_dimensionality-analysis.qmd)
3. [Measurement invariance](04_invariance.qmd)
4. [Reliability and validity](05_reliability.qmd)